// Derives src/data/admin1.ts from data/admin1.json.
//
// Emits one named export per country (`admin1_US`, `admin1_FR`, ...), each a
// readonly array of { value, label } ready to drop into a <select>. Splitting
// into per-country named exports (rather than one big object) is what lets the
// bundler tree-shake away every country that countries.ts doesn't import, so
// the full world's worth of divisions never reaches the published build.
//
//   value -> officialCode (ISO 3166-2) or GeoNames code, country prefix stripped
//   label -> English division name
//
// Run with: bun run scripts/gen-admin1-options.ts
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const inFile = resolve(__dirname, "../data/admin1.json");
const outFile = resolve(__dirname, "../src/data/admin1.ts");

type Division = {
	code: string;
	name: string;
	officialCode: string | null;
};

// "US-NY" -> "NY"; leaves codes without a 2-letter country prefix untouched.
function stripPrefix(code: string): string {
	return code.replace(/^[A-Z]{2}-/, "");
}

const admin1: Record<string, Division[]> = JSON.parse(
	await readFile(inFile, "utf8"),
);

const header = `// AUTO-GENERATED by scripts/gen-admin1-options.ts — do not edit by hand.
// Regenerate with: bun run gen:admin1
// One named export per country so unused divisions tree-shake out of the build.

export type AdministrativeDivisionOption = { value: string; label: string };
`;

const blocks: string[] = [];
for (const code of Object.keys(admin1).sort()) {
	const divisions = [...admin1[code]].sort((a, b) =>
		a.name.localeCompare(b.name),
	);
	const entries = divisions
		.map((d) => {
			const value = stripPrefix(d.officialCode ?? d.code);
			return `\t{ value: ${JSON.stringify(value)}, label: ${JSON.stringify(d.name)} },`;
		})
		.join("\n");
	blocks.push(
		`export const admin1_${code} = [\n${entries}\n] as const satisfies readonly AdministrativeDivisionOption[];`,
	);
}

await writeFile(outFile, `${header}\n${blocks.join("\n\n")}\n`);
console.log(`wrote ${outFile} (${Object.keys(admin1).length} countries)`);
