// Derives src/data/countries.ts from data/countries.json.
//
// Emits a single fully-populated COUNTRY_DATA record (every country, not a
// Partial subset) keyed by ISO 3166-1 alpha-2 code, carrying the reference
// metadata GeoNames gives us — including the admin1/admin2 division-type labels
// that drive level1AdministrativeDivisionLabel in src/utils/address.ts.
//
// Run with: bun run scripts/gen-countries.ts
import { execFile } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);

const __dirname = dirname(fileURLToPath(import.meta.url));
const inFile = resolve(__dirname, "../data/countries.json");
const outFile = resolve(__dirname, "../src/data/countries.ts");

type DivisionType = { en: string | null; local: string | null };
type Country = {
	code: string;
	iso3: string;
	name: string;
	continent: string;
	currencyCode: string;
	currencyName: string;
	postalCodeRegex: string | null;
	languages: string[];
	divisionTypes: {
		admin1: DivisionType | null;
		admin2: DivisionType | null;
	};
};

const countries: Country[] = JSON.parse(await readFile(inFile, "utf8"));
countries.sort((a, b) => a.code.localeCompare(b.code));

// GeoNames reports a single dominant admin1 category, but some countries mix
// two (or more) distinct kinds of level-1 division. For these we override the
// English admin1 label with the combined form so level1AdministrativeDivisionLabel
// in src/utils/address.ts reads correctly. Keyed by alpha-2 code.
const ADMIN1_LABEL_OVERRIDES: Record<string, string> = {
	CA: "Province/Territory",
	AU: "State/Territory",
	VN: "Province/Municipality",
	SL: "Province/Area",
	PA: "Province/Indigenous region",
	KP: "Province/Municipality",
	MM: "Region/State",
	MD: "District/Municipality",
	MY: "State/Federal territory",
	MV: "Atoll/City",
	IE: "County/City",
	ET: "Region/Chartered city",
	AZ: "District/City",
	AG: "Parish/Dependency",
};

for (const c of countries) {
	const override = ADMIN1_LABEL_OVERRIDES[c.code];
	if (override) {
		c.divisionTypes.admin1 = {
			en: override,
			local: c.divisionTypes.admin1?.local ?? null,
		};
	}
}

const header = `// AUTO-GENERATED by scripts/gen-countries.ts — do not edit by hand.
// Regenerate with: bun run gen:countries

export type DivisionType = { en: string | null; local: string | null };

export interface CountryData {
	code: string;
	iso3: string;
	name: string;
	continent: string;
	currencyCode: string;
	currencyName: string;
	postalCodeRegex: string | null;
	languages: string[];
	divisionTypes: {
		admin1: DivisionType | null;
		admin2: DivisionType | null;
	};
}
`;

const entries = countries
	.map((c) => `\t${JSON.stringify(c.code)}: ${JSON.stringify(c)},`)
	.join("\n");

const body = `// Fully populated: every country GeoNames knows about, keyed by alpha-2 code.
export const COUNTRY_DATA: Record<string, CountryData> = {
${entries}
};
`;

await writeFile(outFile, `${header}\n${body}`);
// Biome formats long object literals differently from JSON.stringify; run it so
// the generated file passes `bun run lint` without manual cleanup.
await execFileAsync("bunx", ["biome", "format", "--write", outFile]);
console.log(`wrote ${outFile} (${countries.length} countries)`);
